### ISSUE TITLE
Proposal - plain-hove-focus-active mixin

### ISSUE THREAD

**Issue by Philips7** [7ninjas/scss-mixins#93]
there is no plain-hove-focus-active, can you add it?

**Comment by Nerdy-Girl** [comment]
@Philips7 please describe your issue (ie. what mixin exactly you expect and it's functionality) and I guess you've got typo in title.

**Comment by Philips7** [comment]
this was a proposal to make this mixin because it's missing, according to Serhii we don't need it, but he asked to create issue for that and he will check it

**Comment by Nerdy-Girl** [comment]
@Philips7 cool, but you should describe issue in description so any use (even outside company) can understand it. For now we don't know what functionality it should have (and Serhii is not here to explain it). In some time Serhii or even you can forget what was the purpose.

Issue template is for purpose. So please fit to it and make everyone works easier.

**Comment by Philips7** [comment]
I can not tell you as well if it is a desired functionality or not. I just told it does not exist, but other does. That's why this issue was assigned to Serhii, because he is responsible for this repository. I didn't use template because it is a waste of time if we work in the same company. If have to use long template I would not make issue at all :) Talking about opening issues, I know how it works. Here is an example of one of them:
https://github.com/angular/angular/issues/19903

**Comment by Nerdy-Girl** [comment]
@Philips7 I don't say you don't know how to write issues and I don't say you need to fill every section of template because there is no need of that. I wanted you to write description only. As you can see I also work on this project.

And issues don't mean it's desired functionality or not. It's an idea - enhancement and it should also be described. Is it really so difficult to add short description? Like two sentences what it should do in you opinion.

It's a good practice to describe tasks/issues as you address it to anonymous person who need to understand it. It's not private repository and public users from outside company are also using it and reading issues.

Please write description of your idea for this issue.

**Comment by Philips7** [comment]
I added description and label, but didn't use template is it ok?

**Comment by ArekRado** [comment]
next time please write more information to not waste our time
